version: '3.5'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URI: postgresql+psycopg2://dbchannel:dbchannel@host.docker.internal/dbchannel
    ports: ['5000:5000']
    command: bash -c "cd /src && python manage.py runserver -h 0.0.0.0"

