version: '3.5'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/src
    environment:
      DATABASE_URI: postgresql+psycopg2://dbchannel:dbchannel@host.docker.internal/dbchannel
    ports: ['5000:5000']
    command: bash -c "cd /src && ./scripts/runserver.sh"

