version: '3.5'

services:
  postgres:
    image: postgres:10.5
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports: ['${DB_PORT}:5432']
    restart: on-failure
