version: '3.5'

services:
  postgres:
    image: postgres:10.5
    # env_file:
      # - ./shared_db.env
      # - ./shared_db_${COMPOSE_PROJECT_NAME}.env
      # -local file is not in the repo, but it's where you can make local changes as required
      # due to inflexibility in docker-compose (https://github.com/docker/compose/pull/3955) you either need to touch this file or comment the line out
      # - ./shared_db_${COMPOSE_PROJECT_NAME}_local.env
    environment:
      - DB_PORT=$DB_PORT
    #   - POSTGRES_USER=$DB_USER
    #   - POSTGRES_PASSWORD=$DB_PASSWORD
    #   - POSTGRES_DB=$DB_NAME
    ports: ['${DB_PORT}:5432']
    restart: on-failure
