"""Initial migration.

Revision ID: 4bd072d67d85
Revises: 
Create Date: 2020-04-09 09:58:50.184563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd072d67d85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=8), nullable=True),
    sa.Column('receiver', sa.String(length=8), nullable=True),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('obj', sa.String(length=1024), nullable=True),
    sa.Column('predicate', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
