"""empty message

Revision ID: c4bb473b0441
Revises: 19e4d92b2bef
Create Date: 2020-06-17 06:46:11.880994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4bb473b0441'
down_revision = '19e4d92b2bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'updated_at')
    # ### end Alembic commands ###
