components:
  schemas:
    Message:
      properties:
        id:
          format: int32
          type: integer
        message:
          type: object
        status:
          type: string
      type: object
    MessagePayload:
      properties:
        obj:
          type: string
        predicate:
          type: string
        receiver:
          type: string
        sender:
          type: string
        subject:
          type: string
      required:
      - obj
      - predicate
      - receiver
      - sender
      - subject
      type: object
    PostedMessage:
      properties:
        id:
          format: int32
          readOnly: true
          type: integer
      type: object
    SubscriptionForm:
      properties:
        hub.callback:
          type: string
        hub.lease_seconds:
          default: 432000
          format: int32
          type: integer
        hub.mode:
          enum:
          - subscribe
          - unsubscribe
          type: string
        hub.secret:
          maxLength: 200
          type: string
        hub.topic:
          type: string
      required:
      - hub.callback
      - hub.mode
      - hub.topic
      type: object
info:
  title: Shared DB Channel API
  version: 1.0.0
openapi: 3.0.2
paths:
  /messages:
    post:
      description: Post a new message endpoint
      requestBody:
        content:
          application/json:
            example:
              obj: QmQtYtUS7K1AdKjbuMsmPmPGDLaKL38M5HYwqxW9RKW49n
              predicate: UN.CEFACT.Trade.CertificateOfOrigin.created
              receiver: CN
              sender: AU
              subject: AU.abn0000000000.XXXX-XXXXX-XXXXX-XXXXXX
            schema:
              $ref: '#/components/schemas/MessagePayload'
      responses:
        '201':
          content:
            application/json:
              example:
                id: 1
              schema:
                $ref: '#/components/schemas/PostedMessage'
          description: Returns message id
      servers:
      - url: https://sharedchannel-c1.services.devnet.trustbridge.io/
  /messages/{id}:
    get:
      description: Get message by ID
      parameters:
      - example: 123
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
      - example: id,status,message
        explode: false
        in: query
        name: fields
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        '200':
          content:
            application/json:
              example:
                id: 123
                message:
                  obj: QmQtYtUS7K1AdKjbuMsmPmPGDLaKL38M5HYwqxW9RKW49n
                  predicate: UN.CEFACT.Trade.CertificateOfOrigin.created
                  receiver: CN
                  sender: AU
                  subject: AU.abn0000000000.XXXX-XXXXX-XXXXX-XXXXXX
                status: received
              schema:
                $ref: '#/components/schemas/Message'
          description: Returns message object
      servers:
      - url: https://sharedchannel-c1.services.devnet.trustbridge.io/
  /messages/subscriptions/by_jurisdiction:
    post:
      description: Subscribe to updates about new messages sent to jurisdiction (AU,
        SG, etc.)
      requestBody:
        content:
          application/x-www-form-urlencoded:
            example:
              hub.callback: https://callback.url/1
              hub.mode: subscribe
              hub.topic: AU
            schema:
              $ref: '#/components/schemas/SubscriptionForm'
      responses:
        '202':
          description: Client successfully subscribed/unsubscribed
        '400':
          description: Wrong params or intent verification failure
      servers:
      - url: https://sharedchannel-c1.services.devnet.trustbridge.io/
  /messages/subscriptions/by_id:
    post:
      description: Subscribe to updates about a message (ie. status updates)
      requestBody:
        content:
          application/x-www-form-urlencoded:
            example:
              hub.callback: https://callback.url/1
              hub.mode: subscribe
              hub.topic: 123
            schema:
              $ref: '#/components/schemas/SubscriptionForm'
      responses:
        '202':
          description: Client successfully subscribed/unsubscribed
        '400':
          description: Wrong params or intent verification failure
      servers:
      - url: https://sharedchannel-c1.services.devnet.trustbridge.io/
